exclude: 'node_modules|.git'
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                erpnext/public/dist/.*|
                cypress/.*|
                .*node_modules.*|
                .*boilerplate.*|
                erpnext/public/js/controllers/.*|
                erpnext/templates/pages/order.js|
                erpnext/templates/includes/.*
            )$

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        exclude: ".*node_modules/.*|.*git/.*"

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
